sudo: required
language: go
go:
  - 1.6.1
services:
  - redis-server  
before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mitchellh/gox
script: make test
deploy:
  - provider: script
    script: extras/scripts/travis_packagecloud.sh
    on:
      tags: true 
      go: 1.6.1
