sudo: required

language: go

go:
  # Use quotes to fill in safe:
  # https://github.com/travis-ci/gimme/issues/132
  - '1.9.x'
  - '1.10.x'
  - 'tip'

addons:
  apt:
    packages:
    # needed for the nfpm pipe:
    - rpm

services:
  - docker
  - redis-server  

before_install:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mitchellh/gox

script: make test

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL http://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
      go: '1.10'

